#%RAML 1.0 Trait
responses:
  400:
    description: when request is invalid or incorrect
    body:
      application/json:
        type: errorcodeType
        example: {code: 400, message: "bad request"}