#%RAML 1.0 Trait
description: when trying to post the same record again
responses: 
  409:
    body: 
      application/json:
        type: errorcodeType
        example: {code: 409, message: conflict}