#%RAML 1.0 Trait
description:  Item not found
responses:
  404:
    description: when requested resource is not found
    body:
      application/json:
        type: errorcodeType
        example: {code: 404 , message: <<message>>}