#%RAML 1.0
version: v1
title: Social Media Management (SMM) API
mediaType: application/json
baseUri: http://localhost:8081/smm/
protocols: [HTTP]

/{keyword}:
  description: The base URI parameter for all lists retrieved. Included as the search criteria of the outgoing request
  uriParameters: 
    keyword:
      type: string
      example: "Tuesday"
      required: true
  /tweets:
    description: Retrieve a list of ten or less objects containing the keyword from the URI
    get:
      queryParameters:
        hours:
          description: the number of hours to search through for the keyword.
          type: number
          example: 5
      responses:
        200:
          body:
            application/json:
              example: !include examples/tweetsPayload.json

  /hashtags:
    description: Retrieve a list of hashtags from the ten most popular tweets containing the keyword from the URI
    get:
      responses:
        200:
          body:
            application/json:
              example: !include examples/hashtagsPayload.json